README.md

Fixes a typo in README to link correctly to the CoC page.

Fix Contributor Covenant Link

---

modules/combineReducers.js
modules/effects.js
modules/index.js

Your latest commit that make all internal effect promises resolve an array is cool. It make the Effects.lift very easy to implement.

add Effects.lift

---

modules/combineReducers.js

mapValues should not have side-effects, so the code can either be imperative or it should be using a reduce that always returns a loop. This is using an imperative way as redux function does the same thing.

Remove mapValues from combineReducers

---

modules/install.js

When not the outer enhancer, the next enhancer loses information about the previous ones. In order to fix this issue, we just need to pass the enhancer parameter if received.

Pass the received enhancers to the next enhancer

---

README.md
modules/combineReducers.js
package.json
test/combineReducers.test.js

I returned to a reduce function on the object.keys, as I don't see it being any less efficient, and personally I much prefer it to a for loop, but I kept some of the changes from #36 which did increase efficiency. Let me know what you think.

Addresses #38, combineReducers can handle custom data structures.

---

modules/combineReducers.js

Example of code which cause this issue 
```
function counter(state = { value: 0 }, action) {
switch (action.type) {
case 'INCREMENT':
return {
value: state.value + 1
};
default:
return state;
}
}
const store = createStore(combineReducers({counter}), install());
function select(state) {
return {
value: state.counter.value
};
}
class App extends Component {
handleClick = () => {
this.props.dispatch({
type: 'INCREMENT'
});
}
render() {
const { value } = this.props;
return (
<div>
<p>Value: { value }</p>
<button onClick={ this.handleClick }>Click</button>
</div>
);
}
}
const Root = connect(select)(App);
```

Create new object with default mutator

---

modules/effects.js
modules/install.js
test/index.test.js

This is a potential fix to the issue #64.
There is a test that simulates the behaviour specified in #64 where an action causes an effect, and a store subscriber (e.g. react redux) ends up triggering a component hook which dispatches another action, resulting in the original effect being clobbered with a `NONE` effect.
Please let me know of any improvements I can make to this PR!

FIX #64: Fix dropping of effects by detecting if an effect is already scheduled.

---

README.md

`elm-effects` got moved into `core`, and now commands are part of the language itself. Neat!

Update README (elm-effects is no more)

---

README.md

I'm not certain if I'm being correct, but it seems that the reducer in the example should return the state under the state key, not just the state by itself.

Invalid return value in README example

---

modules/cmd.js
modules/effects.js
modules/index.js
package.json

these will make it easier for people to transition to the new Cmd style api slowly rather than all at once. We should keep them around until version 4.0.
I didn't think it was worth adding the other deprecated effects because they were all just renamed and so it was just find/replace to update them to the new api.

add backwards compatible effects until next major version

---

docs/ApiDocs.md

This updates the API docs so that examples spread the old state (`...state`) when returning new state from a reducer.

Spread old state when creating new state

---

docs/ApiDocs.md

Apologies for mixing the whitespace changes in here, but this makes things a bit more consistent.  The typo corrections are `s/cnd/cmd/g` and `s/Actiion/Action/g` and removing one stray `=`.

Minor API doc typos

---

index.d.ts
test/typescript/loopReducer.ts

Fixes #145 
Removes requirement to specify a union of all sub stores when using combine reducers. Adds a new type parameter to enforce Action types.
```typescript
interface AppState {
foo: FooState;
bar: BarState;
}
interface FooState {
foo: string;
}
interface BarState {
bar: string;
}
```
```typescript
type SubStores = FooState | BarState;
combineReducers<AppState, SubStores>({
foo: reduceFoo,
bar: reduceBar
});
```
```typescript
// can be used with 1 type parameter, like plain redux
combineReducers<AppState>({
foo: reduceFoo,
bar: reduceBar
});
// can be used with 2 type parameters, mirroring the Loop type
type AppAction = FooAction | BarAction;
combineReducers<AppState, AppAction>({
foo: reduceFoo,
bar: reduceBar
});
```
The new type definition can be used in a fashion that is …

Improved TypeScript type definitions for combineReducers

---

index.d.ts

quick fix to the types of interfaces returned by ListCmd and RunCmd -- shouldn't affect many end users because it's mainly just handled internally by `redux-loop`, but `options` gets spread so `args` wouldn't exist inside of an options object here for example:
```
return Object.freeze({
[isCmdSymbol]: true,
type: cmdTypes.RUN,
func,
...options
})
```

fix RunCmd and ListCmd types

---

README.md
docs/ApiDocs.md
index.d.ts
src/combineReducers.js
src/index.js
src/merge-child-reducers.js
test/combineReducers.spec.js
test/merge-child-reducers.spec.js
yarn.lock

I've been using an implementation mergeChildReducers in project I work on for a while and have found it very useful. I think it'd be good for us to expose it as part of the library to ease nesting of reducers for people.
Also, since I broke out immutablejs specific helpers into https://github.com/redux-loop/redux-loop-immutable, I think we should stop supporting a generic combineReducers. They are not as good as custom solutions so I'd rather not enable using them. [Redux does the same thing too](http://redux.js.org/docs/recipes/reducers/BeyondCombineReducers.html).

add mergeChildReducers and deprecate custom combineReducers

---

README.md
docs/ApiDocs.md
index.d.ts
src/cmd.js
test/cmd.spec.js
test/typescript/loopReducer.ts
yarn.lock

Addresses some of the issues in #137. Enables simulation of cmds and disabling invariants for testing matchers.
@gniquil and @jon-thompson I haven't done the tests or doc changes yet. I want to see what you think of this implementation first.
Basically, now you can say
```js
//Cmd.run
expect(getCmd(result).simulate({result: 123, success: true})).toEqual(actionCreator(123));
expect(getCmd(result).simulate({result: 123, success: false})).toBe(null);
//Cmd.actiom
expect(getCmd(result).simulate()).toEqual(actionIPassedToCmd);
//Cmd.list
expect(getCmd(result).simulate([
{result: 123, success: true},
{result: 456, success: false}
])).toEqual([actionCreator1(123), actionCreator2(456]);
```
alternatively, we can expose something like Cmd.simulate(cmd, simulation), but I kind of like it on the cmd …

Improve testing

---

package.json

redux-loop/index.d.ts relies on the `AnyAction` type introduced in `redux@3.7.2` (https://github.com/reactjs/redux/pull/2467#issuecomment-314933101).
AFAIK, the redux-loop implementation itself doesn't depend on features introduced in `3.7.2`.
If we want to keep the peerDependency at `redux@^3.0.0`, an alternate solution would be removing the `AnyAction` import and defining it ourselves. This doesn't seem like that big a deal: https://github.com/reactjs/redux/blob/master/index.d.ts#L25

Upgrade peerDependency for redux to ^3.7.2

---

index.d.ts
src/cmd.js
test/typescript/loopReducer.ts

- Marked `CmdType` properties as readonly, since a frozen object is returned
- Used unique `simulate()` functions on each `CmdType` interface.
- `Cmd` is now a namespace instead of a static class, to reflect that its exported as an object.
- Fixed typescript tests

Made Cmd types more precise

---

src/cmd.js
test/cmd.spec.js

Have redux loop log out errors that occurred within sideEffect functions instead of swallowing them in Cmd.run.
To reproduce the issue, throw an error inside your sideEffect function and notice that the error is being swallowed (not being showed in console). This makes debugging more difficult and hides errors from monitoring services.

fix error swallowing for cmd.run

---

docs/api-docs/install.md
src/cmd.js
src/install.js
test/cmd.spec.js

Add a config option to install.
Currently the only option is `DONT_LOG_ERRORS_ON_HANDLED_FAILURES` (see https://github.com/redux-loop/redux-loop/pull/194, which fixed the issue where error messages were being swallowed in effects when the client added a failActionHandler on a Cmd) which is set to false by default. This means that by default, redux-loop will log errors in your effects even if you pass in a failActionCreator to a command (passing in a failActionCreator does not swallow errors like how `catch` is used for Promises).

add config to control logging of effect errors even when handled

---

docs/tutorial/AdvancedTopics.md

The result of addReducer should be to add the change value (6 in this case) to the state's add property (5 in this case) so it would be 11 and not 30 like you would get from multiplying.

Fix: Show addition result of addReducer in docs

---

index.d.ts
package.json

This adds an optional config object to the install function. It's important because it allows people who are using on Typescript to use the config options.
Based on issue #203

Update type definition of install function to include optional config object

---

src/install.js
test/index.spec.js

The vanilla implementation of redux [passes the provided action back](https://github.com/reduxjs/redux/blob/628ffdd4c5a1b2e4e5b42b26ec8f7b29c344bf0c/src/createStore.js#L208) as a convenience. [The doc comment](https://github.com/reduxjs/redux/blob/628ffdd4c5a1b2e4e5b42b26ec8f7b29c344bf0c/src/createStore.js#L173-L174) does mention that this isn't guaranteed behavior across middleware/store enhancers, but during our transition to `redux-loop` from `redux-thunk`, this characteristic of `dispatch` is important because it was pretty heavily relied on in the past.
Just looking at the code, it's unclear why we do *not* return the provided action. Especially if there are multiple actions in the [cmdRun queue](https://github.com/redux-loop/redux-loop/blob/d811096459104856b4bb7eaf8e8f641b1c23c3fd/sr …

Have dispatch return the action it's provided after the current loop concludes

---

index.d.ts
test/typescript/reduce-reducers.ts

Previously the typescript types for the `reduceReducers` function required all of the reducers to handle the initial `undefined` state, although the actual implementation ensures that only the first reducer to only ever receive an `undefined` state. The types thus forced all the reducers to implement some unnecessary handling for the initial state.
This PR allows all but the first reducer to assume that the state they receive is always initialised.

Relax reduceReducers typing to match implementation

---

index.d.ts
test/typescript/loopReducer.ts

When using defining action creators that return their specific action instead of the union of all actions, there would be a type error with `Cmd.run`
Action creators that return different actions in the union of actions can be using by `Cmd.run()`
Here is an example that breaks with the current typings:
```typescript
interface IFetchFooRequest {
type: typeof FETCH_FOO_REQUEST
}
interface IFetchFooSuccess {
type: typeof FETCH_FOO_SUCCESS
}
const fetchFooSuccess = (): IFetchFooSuccess => ({
type: FETCH_FOO_SUCCESS,
})
interface IFetchFooFailure {
type: typeof FETCH_FOO_FAILURE
}
const fetchFooFailure = (): IFetchFooFailure => ({
type: FETCH_FOO_FAILURE,
})
// --snip--
case FETCH_FOO_REQUEST:
return loop(
state,
Cmd.run(apiFetchFoo, {
successActionCreator: fetchFooSuccess,
failActionCreator: …
```

Update TypeScript types for Cmd.run()

---

index.d.ts
test/typescript/loopReducer.ts

This patch fixes the TypeScript definition of `StoreCreator` to make `preloadedState` optional.
Why? I'll explain.
Here is a TypeScript version of the documented way to create a store:
```js
import { createStore } from 'redux';
import { StoreCreator, install } from 'redux-loop';
import reducer from './reducer';
type ApplicationState = {};
const initialState: ApplicationState = { /* ... */ };
const enhancedCreateStore = createStore as StoreCreator;
const store = enhancedCreateStore(
reducer, initialState, install<ApplicationState>()
);
```
However, `initialState` is optional in [createStore](https://redux.js.org/api/createstore). This should be possible:
```js
const store = enhancedCreateStore(
reducer, undefined, install<ApplicationState>()
);
```
Yet it produces an error that looks …

Fix StoreCreator TypeScript def to match redux

---

test/typescript.spec.js

I noticed that the TypeScript tests aren't working. Here's a patch that should trigger a test failure:
```diff
diff --git a/index.d.ts b/index.d.ts
index fa84b3e..b788e7c 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -3,7 +3,7 @@ import { Action, ActionCreator, AnyAction, StoreEnhancer, Store } from 'redux';
export interface StoreCreator {
<S, A extends Action>(
reducer: LoopReducer<S, A>,
-    preloadedState: S | undefined,
+    preloadedState?: S | undefined,
enhancer: StoreEnhancer<S>
): Store<S>;
}
```
Only after passing the error to `done()` (which totally [isn't documented correctly](https://github.com/adamcarr/typescript-definition-tester)), I get a test failure:
```
FAIL  test/typescript.spec.js
● Console
console.log node_modules/typescript-definition-tester/dist/index.js:28
Global …
```

Fix TypeScript tests so they fail for errors 😭

---

index.d.ts

`Reducer` in Redux is defined like so:
```typescript
export type Reducer<S = any, A extends Action = AnyAction> = (
state: S | undefined,
action: A
) => S
```
I think it would be better to define `LoopReducer` in a similar way so the action type is taken from the parameter and the parameter has the same default as `Reducer`

Better typings for reducers

---

index.d.ts

Been using redux-loop extensively and recently introduced TypeScript to one of my projects. I noticed that the type for testInvariants for Cmd.run's options is missing, so I added it. Thanks!

Add type for Cmd.run's options.testInvariants.

---

index.d.ts

Typescript 2.7 added `unique symbol` to describe symbol types which are unique. Otherwise the types of Cmd.getState and Cmd.dispatch are assignable to each other.

unique symbol type for Cmd.getState, Cmd.dispatch

---

index.d.ts

The current typescript declarations seem to be a strange mix of [global declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html) and [module declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html). As the package is intended to be used as a module, the appropriate declaration style is to use the `export` keyword when defining the elements of the module.
This is similar to the style for example the react-redux package [types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts) uses.

Fix typescript declaration style

---

index.d.ts
test/typescript/loopReducer.ts

I notice there is a stale PR that tackles the same problem.
This PR goes a step further with argument inference while still allowing the special symbols to be used if the fn passed has arguments that would match the types of Dispatch or GetState (although I can't distinguish between them as the type symbol === symbol)

Make Cmd.run typesafe

---

docs/api-docs/cmds.md
src/cmd.js
src/install.js
test/cmd.spec.js

@laszlopandy this should address the list issue from #218

Wrap actions from unbatched lists in the tagger from Cmd.map

---

src/cmd.js
src/install.js
test/cmd.spec.js

Use a context object for the (mostly) unchanging parameters used by `executeCmd` and its helper functions.
@bdwain This is more what I meant regarding passing the extra parameters in an object. `context` might be the wrong name, but I think this makes the code cleaner.

executeCmd uses context object to avoid repetition

---

.eslintrc
index.d.ts
package.json
test/typescript/loopReducer.ts
test/typescript/reduce-reducers.ts
yarn.lock

As discussed in issue https://github.com/redux-loop/redux-loop/issues/243 actions are not always dispatched from loops. This PR defaults the `Action` generic to `never` in the various spots where an action may not be dispatched.

Adjust TypeScript definition for places where actions may not be dispatched

---

index.d.ts

1. Export `WithDefaultActionHandling`, otherwise it is impossible to explicitly specify a correct type for your reducer's arguments, like so:
```
function reducer(state: State, action: WithDefaultActionHandling<Action>): State | Loop<State> { ... }
```
2. Allow specifying the generic types of `Dispatch` and `GetState`.
Both of these changes are fully backwards compatible.

Typescript fixes: export WithDefaultActionHandling, fix generics
